create table public.djangoapp_position
(
    id          integer generated by default as identity
        primary key,
    description varchar(100) not null
);

alter table public.djangoapp_position
    owner to admin;

create table public.djangoapp_professional
(
    id          integer generated by default as identity
        primary key,
    name        varchar(200) not null,
    position_id integer      not null
        constraint djangoapp_profession_position_id_602c7012_fk_djangoapp
            references public.djangoapp_position
            deferrable initially deferred
);

alter table public.djangoapp_professional
    owner to admin;

create index djangoapp_professional_position_id_602c7012
    on public.djangoapp_professional (position_id);


